version: '3'

services:
  db:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=root
    volumes:
        - ./sql/db_users.sql:/docker-entrypoint-initdb.d/db_users.sql




