version: '3'

services:
  db:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=secure_users
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
        - ./sql/db_users.sql:/docker-entrypoint-initdb.d/db_users.sql




